/**
 * Bridge to the local agent-webhook-bridge install: the hub creates hooks by
 * writing awb's hooks.json directly — the broker re-reads that file on every
 * request, so a hook registered here is live immediately, no restart. Same
 * file format `awb add` writes (agent-webhook-bridge/broker/config.ts); the
 * hub only ever adds "trigger" hooks with the fields the mesh needs.
 *
 * This only works while hub and broker share a machine (phase 1). Remote
 * nodes in phase 2 will register their own hooks and use the "existing hook"
 * path instead.
 */
import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

interface AwbConfig {
	host: string;
	port: number;
	maxBodyBytes: number;
	publicBaseUrl: string | null;
	hooks: Record<string, Record<string, unknown>>;
}

// Mirrors awb's own defaults so a machine where the broker has never saved
// its config yet still gets a valid hooks.json.
const AWB_DEFAULTS: Omit<AwbConfig, "hooks"> = {
	host: "127.0.0.1",
	port: 8890,
	maxBodyBytes: 1024 * 1024,
	publicBaseUrl: null,
};

function awbConfigFile(): string {
	return path.join(process.env.AWB_HOME ?? path.join(os.homedir(), ".agent-webhook-bridge"), "hooks.json");
}

function loadAwbConfig(): AwbConfig {
	let fileCfg: Partial<AwbConfig> = {};
	try {
		fileCfg = JSON.parse(fs.readFileSync(awbConfigFile(), "utf8")) as Partial<AwbConfig>;
	} catch {
		// Missing/invalid config file → fall back to defaults.
	}
	return { ...AWB_DEFAULTS, ...fileCfg, hooks: { ...(fileCfg.hooks ?? {}) } };
}

export class HookExistsError extends Error {}

export interface LocalHookInfo {
	/** false when the URL doesn't point at this machine's awb broker. */
	local: boolean;
	found?: boolean;
	name?: string;
	hasWorkdir?: boolean;
}

/**
 * Looks a hook URL up in the local awb config, so registration can warn
 * about hooks that don't exist or lack a workdir (a workdir-less hook runs
 * in whatever folder the broker was started from, which moves its Claude
 * sessions — and its project context — across broker restarts). Remote URLs
 * come back `local: false` and are never judged: phase 2 nodes manage their
 * own hooks.
 */
export function inspectLocalHook(hookUrl: string): LocalHookInfo {
	let url: URL;
	try {
		url = new URL(hookUrl);
	} catch {
		return { local: false };
	}
	const cfg = loadAwbConfig();
	const loopback = new Set(["127.0.0.1", "localhost", "[::1]"]);
	if (!loopback.has(url.hostname) || Number(url.port || 80) !== cfg.port) return { local: false };
	const parts = url.pathname.split("/").filter(Boolean);
	if (parts[0] !== "hook" || !parts[1]) return { local: false };
	const name = decodeURIComponent(parts[1]);
	const hook = cfg.hooks[name];
	if (!hook) return { local: true, found: false, name };
	return { local: true, found: true, name, hasWorkdir: typeof hook.workdir === "string" && hook.workdir !== "" };
}

export interface HookRuntime {
	/** Harness the hook spawns, from its `consumers` list (`spawn:claude` → "claude"). */
	harness: string | null;
	/** Directory the harness runs in — where its sessions can be resumed from. */
	workdir: string | null;
}

/**
 * How the hook runs its jobs. Only answerable for hooks on this machine's
 * broker; remote hooks (phase 2) come back all-null. The workdir is a local
 * path, which is fine to expose while the hub is local-only.
 */
export function hookRuntime(hookUrl: string): HookRuntime {
	const info = inspectLocalHook(hookUrl);
	if (!info.local || !info.found || !info.name) return { harness: null, workdir: null };
	const hook = loadAwbConfig().hooks[info.name];
	const consumers = Array.isArray(hook?.consumers) ? (hook.consumers as unknown[]) : [];
	let harness: string | null = null;
	for (const consumer of consumers) {
		if (typeof consumer === "string" && consumer.startsWith("spawn:")) {
			harness = consumer.slice("spawn:".length);
			break;
		}
	}
	const workdir = typeof hook?.workdir === "string" && hook.workdir !== "" ? hook.workdir : null;
	return { harness, workdir };
}

/**
 * Permission modes the hub is willing to write into a hook — the full awb
 * list. `bypassPermissions` lets anyone who can submit a job run arbitrary
 * Bash on the operator's machine, so the publish endpoint only accepts it
 * together with an explicit `acceptBypassRisk: true` (the UI asks for a
 * confirmation before sending it) — never a silent default.
 */
export const PUBLISHABLE_PERMISSION_MODES = ["acceptEdits", "auto", "manual", "dontAsk", "plan", "bypassPermissions"] as const;
export type PublishablePermissionMode = (typeof PUBLISHABLE_PERMISSION_MODES)[number];

export interface HookOptions {
	/** Custom shared secret; autogenerated when omitted. */
	secret?: string;
	permissionMode?: PublishablePermissionMode;
}

/**
 * Registers a new trigger hook in awb and returns what the hub needs to
 * point an agent at it. Creates the workdir if it doesn't exist yet.
 */
export function createAwbHook(
	name: string,
	workdir: string,
	promptTemplate: string,
	options: HookOptions = {},
): { hookUrl: string; secret: string } {
	const cfg = loadAwbConfig();
	if (cfg.hooks[name]) throw new HookExistsError(`awb hook '${name}' already exists`);

	const secret = options.secret ?? crypto.randomBytes(24).toString("hex");
	fs.mkdirSync(workdir, { recursive: true });
	cfg.hooks[name] = {
		mode: "trigger",
		consumers: ["spawn:claude"],
		secret,
		promptTemplate,
		workdir,
		...(options.permissionMode ? { permissionMode: options.permissionMode } : {}),
	};
	const file = awbConfigFile();
	fs.mkdirSync(path.dirname(file), { recursive: true });
	fs.writeFileSync(file, `${JSON.stringify(cfg, null, 2)}\n`);

	return { hookUrl: `http://${cfg.host}:${cfg.port}/hook/${encodeURIComponent(name)}`, secret };
}

/**
 * Removes a hook from awb's hooks.json, e.g. when its owning workflow is
 * deleted. Best-effort: never throws, just reports whether it found (and
 * removed) the hook, so a workflow whose hook is already gone can still be
 * deleted cleanly.
 */
export function deleteAwbHook(name: string): boolean {
	try {
		const cfg = loadAwbConfig();
		if (!cfg.hooks[name]) return false;
		delete cfg.hooks[name];
		const file = awbConfigFile();
		fs.mkdirSync(path.dirname(file), { recursive: true });
		fs.writeFileSync(file, `${JSON.stringify(cfg, null, 2)}\n`);
		return true;
	} catch {
		return false;
	}
}
